platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: source

outputs:
- name: package

run:
    path: sh
    args:
      - -exc
      - |
        pwd
        ls -l
        tar --exclude='.git' -czvf package/cra-noise-proxy.tar.gz source
        ls -l package
        tar -tvf package/cra-noise-proxy.tar.gz